services:
  app:
    image: ghcr.io/nov1ce-lee/mc-website:latest
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      DATABASE_URL: file:/app/prisma/data/dev.db
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MC_SERVER_IP: ${MC_SERVER_IP}
    volumes:
      - sqlite_data:/app/prisma/data
    command: >
      sh -c "npx prisma db push && npm start"

volumes:
  sqlite_data:
